# Generated by Django 4.1.7 on 2023-03-03 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата совершения обмена')),
                ('description', models.TextField(verbose_name='Описание/Условия обмена')),
                ('assessment', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка обмена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность сделки')),
                ('is_end', models.BooleanField(default=False, verbose_name='Окончание сделки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обмен',
                'verbose_name_plural': 'Обмены',
            },
        ),
        migrations.CreateModel(
            name='SwapHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swaps', models.ManyToManyField(to='swap_app.swap', verbose_name='Обмены')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swap_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'История обменов',
            },
        ),
    ]
