# Generated by Django 4.1.7 on 2023-03-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swap',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата совершения обмена'),
        ),
    ]
