"""add is_active field for user table

Revision ID: 094a7d61ff7f
Revises: d46292cdd2b1
Create Date: 2023-01-06 04:25:18.380598

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "094a7d61ff7f"
down_revision = "d46292cdd2b1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.alter_column("user", "phone", existing_type=sa.VARCHAR(length=18), nullable=True)
    op.create_index(op.f("ix_user_is_active"), "user", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_is_active"), table_name="user")
    op.alter_column(
        "user", "phone", existing_type=sa.VARCHAR(length=18), nullable=False
    )
    op.drop_column("user", "is_active")
    # ### end Alembic commands ###
