"""Add age column and do email is unique

Revision ID: 28f6b0496853
Revises: 094a7d61ff7f
Create Date: 2023-01-22 03:10:37.220985

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "28f6b0496853"
down_revision = "094a7d61ff7f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("age", sa.Integer(), nullable=False))
    op.create_unique_constraint(None, "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "age")
    # ### end Alembic commands ###
