"""Add password column in user table

Revision ID: da3e617f4750
Revises: 28f6b0496853
Create Date: 2023-01-22 16:33:31.909677

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "da3e617f4750"
down_revision = "28f6b0496853"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("password", sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password")
    # ### end Alembic commands ###
