# Generated by Django 4.1.5 on 2023-01-29 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Swap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата совершения обмена"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Описание/Условия обмена"),
                ),
                (
                    "assessment",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Оценка обмена"
                    ),
                ),
            ],
            options={
                "verbose_name": "Обмен",
                "verbose_name_plural": "Обмены",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, verbose_name="Имя")),
                ("surname", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Отчество"
                    ),
                ),
                ("age", models.PositiveIntegerField(verbose_name="Возраст")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=18, null=True, verbose_name="Телефон"
                    ),
                ),
                ("rating", models.FloatField(default=0, verbose_name="Рейтинг")),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
        migrations.CreateModel(
            name="SwapHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "swaps",
                    models.ManyToManyField(
                        to="app_profile.swap", verbose_name="Обмены"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_history",
                        to="app_profile.userprofile",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "История обменов",
            },
        ),
        migrations.AddField(
            model_name="swap",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swaps",
                to="app_profile.userprofile",
                verbose_name="Пользователь",
            ),
        ),
    ]
