# Generated by Django 4.1.5 on 2023-01-28 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Swap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата совершения обмена"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Описание/Условия обмена"),
                ),
            ],
            options={
                "verbose_name": "Обмен",
                "verbose_name_plural": "Обмены",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("surname", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("age", models.IntegerField(verbose_name="Возраст")),
                (
                    "phone",
                    models.CharField(max_length=18, null=True, verbose_name="Телефон"),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="SwapHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "swaps",
                    models.ManyToManyField(
                        to="app_profile.swap", verbose_name="Обмены"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_profile.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "История обменов",
            },
        ),
        migrations.AddField(
            model_name="swap",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_profile.user",
                verbose_name="Пользователь",
            ),
        ),
    ]
