# Generated by Django 4.1.5 on 2023-01-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_profile", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="swap",
            old_name="user",
            new_name="user_profile",
        ),
        migrations.RenameField(
            model_name="swaphistory",
            old_name="user",
            new_name="user_profile",
        ),
    ]
