# Generated by Django 4.1.5 on 2023-01-29 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swaphistory",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_profile.user",
                verbose_name="Пользователь",
            ),
        ),
    ]
