# Generated by Django 4.1.5 on 2023-01-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_profile", "0002_rename_user_swap_user_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="swap",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активность сделки"),
        ),
        migrations.AddField(
            model_name="swap",
            name="is_end",
            field=models.BooleanField(default=False, verbose_name="Окончание сделки"),
        ),
    ]
