"""remove surname, patronymic, age

Revision ID: 82ec3e00ccc8
Revises: 2b3ac56c1f53
Create Date: 2023-02-18 18:03:08.569683

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "82ec3e00ccc8"
down_revision = "2b3ac56c1f53"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "patronymic")
    op.drop_column("user", "surname")
    op.drop_column("user", "age")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "user",
        sa.Column(
            "surname", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "patronymic", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
