"""init migrations

Revision ID: d46292cdd2b1
Revises: 
Create Date: 2023-01-05 04:04:46.790770

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d46292cdd2b1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("surname", sa.String(length=100), nullable=False),
        sa.Column("patronymic", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=18), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "code",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column("value", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user"], ["user.id"], name="fk_code_user_id_user"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user"),
    )
    op.create_table(
        "token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["user"], ["user.id"], name="fk_token_user_id_user"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("value"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token")
    op.drop_table("code")
    op.drop_table("user")
    # ### end Alembic commands ###
